#!/usr/bin/env node
/**
 * Regenerate the ADR index table in docs/decisions/README.md.
 *
 * The index is generated rather than hand-kept because a hand-maintained table
 * is one forgotten edit away from lying, and an index that lies is worse than
 * no index — readers stop trusting it, then stop using it. The index is the
 * discovery surface: it is how a reader, or an agent about to change something
 * load-bearing, finds out that a decision exists.
 *
 * Nothing is duplicated into frontmatter. Each record already carries its
 * number and title in the H1 and its status in the header line. Restating
 * either above the fold would create two sources of truth that drift apart —
 * frontmatter reading `Accepted` above a body reading `Superseded by 0012`,
 * with no way to tell which is current.
 *
 * Optionally, a record may carry one italic sentence directly beneath the
 * header saying what it is for. That line orients anyone opening the file and
 * is harvested into the index. Records written before the convention simply
 * leave the cell empty; the run reports how many, so the gap is visible rather
 * than silent.
 *
 * Plain Node rather than TypeScript on purpose: this repo has no tsx, and
 * adding a toolchain dependency to run one script is a poor trade.
 *
 * Usage:
 *   node scripts/adr-index.mjs           rewrite the table
 *   node scripts/adr-index.mjs --check   exit 1 if the table is out of date
 */

import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const DECISIONS_DIR = join(REPO_ROOT, 'docs', 'decisions')
const README = join(DECISIONS_DIR, 'README.md')

const START = '<!-- adr-index:start -->'
const END = '<!-- adr-index:end -->'

/** `# 0002 — Preflight and Flight are isolated packages` */
const H1 = /^#\s+(\d{4})\s+[—-]\s+(.+?)\s*$/m
/** `**Date:** 2026-07-25 · **Status:** Accepted · **Supersedes** …` */
const STATUS = /\*\*Status:\*\*\s*([^·\n]+?)(?:\s*·|\s*$)/m
/** The optional italic one-liner directly beneath the header line. */
const SUMMARY = /^\s*_(.+?)_\s*$/m

function parse(file) {
  const raw = readFileSync(join(DECISIONS_DIR, file), 'utf-8')
  const h1 = H1.exec(raw)
  if (!h1) {
    console.warn(`  ⚠ ${file}: no "# NNNN — Title" heading; skipped`)
    return null
  }
  return {
    num: h1[1],
    title: h1[2],
    status: STATUS.exec(raw)?.[1]?.trim() ?? 'Unknown',
    summary: SUMMARY.exec(raw)?.[1]?.trim() ?? '',
    file,
  }
}

function render(adrs) {
  const rows = adrs.map((a) => {
    // A superseded decision must read as superseded at a glance, or someone
    // acts on a record that has already been reversed.
    const status = /^Superseded/i.test(a.status) ? `~~${a.status}~~` : a.status
    return `| [${a.num}](${a.file}) | **${a.title}** | ${status} | ${a.summary} |`
  })
  return [
    START,
    '',
    '| # | Decision | Status | |',
    '|---|---|---|---|',
    ...rows,
    '',
    `_${adrs.length} record${adrs.length === 1 ? '' : 's'}. Generated by \`pnpm adr:index\` — edit the ADRs, not this table._`,
    END,
  ].join('\n')
}

function main() {
  const check = process.argv.slice(2).includes('--check')

  const files = readdirSync(DECISIONS_DIR)
    .filter((f) => /^\d{4}-.*\.md$/.test(f))
    .sort()

  const adrs = files.map(parse).filter(Boolean)

  const readme = readFileSync(README, 'utf-8')
  const s = readme.indexOf(START)
  const e = readme.indexOf(END)
  if (s === -1 || e === -1) {
    console.error(`${README} is missing the ${START} / ${END} markers.`)
    process.exit(1)
  }

  const next = readme.slice(0, s) + render(adrs) + readme.slice(e + END.length)
  const missing = adrs.filter((a) => !a.summary).length

  if (next === readme) {
    console.log(`Index is current — ${adrs.length} record(s).`)
    if (missing) console.log(`${missing} without a summary line (optional).`)
    return
  }

  if (check) {
    console.error('ADR index is out of date. Run: pnpm adr:index')
    process.exit(1)
  }

  writeFileSync(README, next, 'utf-8')
  console.log(`Rewrote the index — ${adrs.length} record(s).`)
  if (missing) console.log(`${missing} without a summary line (optional).`)
}

main()
